repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: end-of-file-fixer
        exclude: ^fixtures/data/
      - id: trailing-whitespace
        exclude: ^fixtures/data/
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^fixtures/data/

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.4
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace --all-targets -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
        stages: [pre-push]
