[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/abkfenris/gridded-quicklook"

[workspace.dependencies]
gridlook-meta = { path = "crates/gridlook-meta" }
gridlook-html = { path = "crates/gridlook-html" }
