[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/abkfenris/gridded-quicklook"

[workspace.dependencies]
gridded-meta = { path = "crates/gridded-meta" }
gridded-html = { path = "crates/gridded-html" }
